### PR TITLE
Print DRF errors upon invalid serialization.

### PR DESCRIPTION
**Pull request by doctoryes**
https://openedx.atlassian.net/browse/LEARNER-1977

@iloveagent57 FYI

### CODE REVIEW

**Comment by doctoryes** [comment]
@efischer19 @iloveagent57 I'm going to go ahead and merge this to get the edx-platform work started for this CAT-2 bug above. Please review it anyway.

**Comment by iloveagent57** [comment]
I noticed earlier today that the `__version__` in `submissions/__init__.py` is stale, so if you have an opportunity to bump the version there, too... :)

**Comment by iloveagent57** [comment]
`__version__` aside, this LGTM, too.

**Comment by doctoryes** [comment]
We should simply delete one of those versions - probably using the __init__.py version is the way to go, reading/using that value in setup.py. I didn't see this in time to fix it my latest submissions PR. ☹️

**Pull request merged**
