### PR TITLE
SQL logging

### PR DESCRIPTION
**Pull request by efischer19**
Don't merge, just getting some data about our SQL usage

### CODE REVIEW

**Comment by edx-webhook** [comment]
## PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

## Sandbox
- [ ] Build a sandbox for your branch and add a link here

## Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

## Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] Docs review (required for UI strings/error messages)
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

## Documentation considerations
- [ ] Are there user visible changes? If so, list who is affected, and include a pointer to the relevant code.
- [ ] Should this be mentioned in the release notes? If so, make sure that you included a description.

## DevOps assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

## Post-review
- [ ] Squash commits

**Comment by efischer19** [comment]
```
SELECT
"submissions_submission"."id", "submissions_submission"."uuid", "submissions_submission"."student_item_id", "submissions_submission"."attempt_number", "submissions_submission"."submitted_at", "submissions_submission"."created_at", "submissions_submission"."raw_answer", "submissions_submission"."status", "submissions_studentitem"."id", "submissions_studentitem"."student_id", "submissions_studentitem"."course_id", "submissions_studentitem"."item_id", "submissions_studentitem"."item_type", "submissions_scoresummary"."id", "submissions_scoresummary"."student_item_id", "submissions_scoresummary"."highest_id", "submissions_scoresummary"."latest_id", "submissions_score"."id", "submissions_score"."student_item_id", "submissions_score"."submission_id", "submissions_score"."points_earned", "submissions_score"."points_possible", "submissions_score"."created_at", "submissions_score"."reset", T5."id", T5."uuid", T5."student_item_id", T5."attempt_number", T5."submitted_at", T5."created_at", T5."raw_answer", T5."status"
FROM
"submissions_submission"
INNER JOIN "submissions_studentitem" ON ( "submissions_submission"."student_item_id" = "submissions_studentitem"."id" )
LEFT OUTER JOIN "submissions_scoresummary" ON ( "submissions_studentitem"."id" = "submissions_scoresummary"."student_item_id" )
LEFT OUTER JOIN "submissions_score" ON ( "submissions_scoresummary"."latest_id" = "submissions_score"."id" )
LEFT OUTER JOIN "submissions_submission" T5 ON ( "submissions_score"."submission_id" = T5."id" )
WHERE 
(NOT ("submissions_submission"."status" = D) AND "submissions_studentitem"."item_type" = Peer_Submission AND "submissions_studentitem"."course_id" = Demo_Course) ORDER BY "submissions_submission"."submitted_at" DESC, "submissions_submission"."id"
DESC
'''

**Comment by efischer19** [comment]
So the `Submission` -> `StudentItem` relationship is an INNER join, and all the rest are OUTERs. I believe this is due to `StudentItem` -> `ScoreSummary` being a reverse OneToOne relationship, so there may or may not be any data from that point on in the relationship chain.

**Comment by robrap** [comment]
Thanks for this @efischer19.

**Pull request closed without merging**
