### PR TITLE
INCR-183: Fix comparison of float and None

### PR DESCRIPTION
**Pull request by anthonywee**
In Python 3 it's no longer valid to compare a float with None.

Ref: https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @anthonywee! I've created [OSPR-3382](https://openedx.atlassian.net/browse/OSPR-3382) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by anthonywee** [comment]
@edx/incr-reviewers

**Comment by natabene** [comment]
@anthonywee Thank you for your contribution. @edx/incr-reviewers Looks like this is ready for your review.

**Comment by edx-webhook** [comment]
@anthonywee 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-submissions&entry.867055334=https://github.com/edx/edx-submissions/pull/96&entry.1484655318=https://github.com/anthonywee&entry.752974735=2019-05-06+22:32&entry.1917517419=2019-05-07+19:45&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
